services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/pgsql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3333:3333
    environment:
      APP_PORT: 3333
      DATABASE_URL: postgresql://postgres:postgres@db:5432/database_test
      AT_SECRET: AT_sECRET
      RT_SECRET: RT_sECRET
      TK_EMAIL_SECRET: EMAIL_sECRET
      TK_EMAIL_LIFETIME: 1d
      JWT_ACCESS_LIFETIME: 1h
      JWT_REFRESH_LIFETIME: 7d
      ENV: TEST
      SENDGRID_API_KEY: ""
      EMAIL_OPTIONS_FROM: ""
volumes:
  db: