name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Build
        run: |
          npm install
          npm run build
          echo "Build finished"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Image published $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Generate container configuration JSON from template
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
          AT_SECRET: ${{ secrets.AT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_OPTIONS_FROM: ${{ secrets.EMAIL_OPTIONS_FROM }}
          RT_SECRET: ${{ secrets.RT_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TK_EMAIL_SECRET: ${{ secrets.TK_EMAIL_SECRET }}
          LIGHTSAIL_SERVICE_NAME: ${{ secrets.LIGHTSAIL_SERVICE_NAME }}
          API_CORREIOS_URL: ${{ vars.API_CORREIOS_URL }}
          APP_PORT: ${{ vars.APP_PORT }}
          ENV: ${{ vars.ENV }}
          FRONTEND_RECOVER_PASSWORD_URL: ${{ vars.FRONTEND_RECOVER_PASSWORD_URL }}
          FRONT_END_URL: ${{ vars.FRONT_END_URL }}
          JWT_ACCESS_LIFETIME: ${{ vars.JWT_ACCESS_LIFETIME }}
          JWT_REFRESH_LIFETIME: ${{ vars.JWT_REFRESH_LIFETIME }}
          TK_EMAIL_LIFETIME: ${{ vars.TK_EMAIL_LIFETIME }}
        run: |
          export CONFIG_FILE=update-service.json
          export FULL_IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          chmod +x replace-vars.sh
          ./replace-vars.sh
          cat $CONFIG_FILE

      - name: Update Lightsail container service
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lightsail create-container-service-deployment --cli-input-json file://update-service.json
